### ISSUE TITLE
Review percents/read counts to make sure they are consistent

### ISSUE THREAD

**Issue by apetkau** [phac-nml/speciesabundance#15]
### Description of feature

We should review read counts and percentages of Kraken2, Bracken, and the adjusted Bracken outputs to make sure they are all consistent and match.

**Comment by kylacochrane** [comment]
I went through the test data and ran additional fastq files (downloaded from EMBL) through SpeciesAbundance on my local computer (and on IRIDA Next) to verify the read counts and percentages:

- All of the reports line up in terms of expected reads and percentages/proportions.

- **HOWEVER** - I found an error in the adjusted data for the bracken_abundances.csv and the error was therefore transferred to the merged_topN.csv (which is used by the IRIDANext plugin): The adjust_bracken_for_unclassified_reads.py pulls the "num_seq_this_clade" from the Kraken2 report, instead of the Bracken report!  

A PR will be generated and linked here with the required changes ASAP!
